name: Plan using Terraform
on:
  pull_request:
jobs:
  terraform_workflow:
    name: Terraform Workflow
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      TF_VAR_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_access_key_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      TF_IN_AUTOMATION: true
      TF_ROOT: /
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        
      - name: tfsec
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt
        continue-on-error: true

      - name: Initialize Terraform
        id: init
        run: |
          terraform init \
          -backend-config="access_key="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -backend-config="secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
          terraform plan -no-color -out tfplan.binary


      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Tfsec 🤖\`${{ steps.tfsec.outcome }}\'
            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
